# Generated by Django 5.2.2 on 2025-06-08 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LunchBreakClassAssignment',
            new_name='BreakClassAssignment',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='capable_upto_class',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='is_class_teacher',
        ),
        migrations.AddField(
            model_name='teacher',
            name='capable_classes',
            field=models.ManyToManyField(blank=True, to='BackendApp.classroom'),
        ),
    ]
