# Generated by Django 5.2.2 on 2025-06-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BackendApp', '0002_rename_lunchbreakclassassignment_breakclassassignment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='capable_classes',
            new_name='capable_classes_for_proxy',
        ),
    ]
