# Generated by Django 5.2.2 on 2025-06-15 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='name1',
        ),
    ]
