# Generated by Django 5.2.2 on 2025-06-18 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_dailylecturetiming_lecture_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='breakclassassignment',
            old_name='classroom',
            new_name='classrooms',
        ),
        migrations.AlterUniqueTogether(
            name='breakclassassignment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='breakclassassignment',
            name='break_type',
            field=models.CharField(default='Lunch Break', max_length=50),
        ),
        migrations.AddField(
            model_name='breakclassassignment',
            name='max_grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='breakclassassignment',
            name='min_grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
