# Generated by Django 5.2.2 on 2025-06-19 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_remove_breakclassassignment_break_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakclassassignment',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='breakclassassignment',
            name='break_type',
            field=models.CharField(default='Lunch Break', max_length=50),
        ),
    ]
