# Generated by Django 5.2.2 on 2025-06-19 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0006_remove_breakclassassignment_classrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakclassassignment',
            name='break_type',
        ),
    ]
