# Generated by Django 5.2.2 on 2025-06-19 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0008_breakclassassignment_break_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakclassassignment',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='breakclassassignment',
            name='classrooms',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Backend.classroom'),
            preserve_default=False,
        ),
    ]
