# Generated by Django 5.2.2 on 2025-06-19 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0009_remove_breakclassassignment_classrooms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakclassassignment',
            name='classrooms',
        ),
        migrations.AddField(
            model_name='breakclassassignment',
            name='classrooms',
            field=models.ManyToManyField(to='Backend.classroom'),
        ),
    ]
