# Generated by Django 5.2.2 on 2025-06-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0010_remove_breakclassassignment_classrooms_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lectureschedule',
            options={'ordering': ['day', 'lecture_timing__lecture_number']},
        ),
        migrations.AlterUniqueTogether(
            name='lectureschedule',
            unique_together={('day', 'lecture_timing', 'classroom')},
        ),
        migrations.RemoveField(
            model_name='lectureschedule',
            name='date',
        ),
    ]
